version: '3'

env:
  APP_NAME: nm-jira

dotenv: ['.env']

tasks:

  default:
    desc: Run the built binary
    deps: [build]
    cmds:
      - ./bin/{{.APP_NAME}}

  build:
    desc: Build the binary
    cmds:
      - go build -o bin/{{.APP_NAME}} ./cmd/jira

  lint:
    desc: Run static analysis
    cmds:
      - golangci-lint run ./...
